unit BrickCamp.Model.TUser;

interface

uses
  Spring,
  Spring.Persistence.Mapping.Attributes,
  BrickCamp.Model.IProduct;

type
  [Entity]
  [Table('CUSER')]
  TUser = class
  private
    [Column('ID', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'primary key')]
    [AutoGenerated]
    FId: Integer;
  private
    FName: string;

    function GetId: Integer;
    function GetName: string;
    procedure SetName(const Value: string);
  public
    constructor Create(const Id: integer); reintroduce;

    property ID: Integer read GetId;

    [Column('NAME', [cpNotNull])]
    property Name: string read GetName write SetName;
  end;

implementation

{ TEmployee }

constructor TUser.Create(const Id: integer);
begin
  FId := Id;
end;

function TUser.GetId: Integer;
begin
  Result := FId;
end;

function TUser.GetName: string;
begin
  Result := FName;
end;

procedure TUser.SetName(const Value: string);
begin
  FName := Value;
end;

end.

