unit BrickCamp.Model.Employee;

interface

uses
  Spring,
  Spring.Persistence.Mapping.Attributes;

type
  [Entity]
  [Table('EMPLOYEE')]
  TEmployee = class
  private
    [Column('EMP_NO', [cpRequired, cpPrimaryKey, cpNotNull, cpDontInsert], 0, 0, 0, 'primary key')]
    [AutoGenerated]
    FId: Integer;
  private
    FFirstName: string;
    FLastName: string;
    FPhoneExt: Nullable<string>;
    FHireDate: TDateTime;
    FDepartmentNumber: string;
    FJobCode: string;
    FJobGrade: SmallInt;
    FJobCountry: string;
    FSalary: Extended;
  public
    property ID: Integer read FId;

    [Column('FIRST_NAME', [cpNotNull])]
    property FirstName: string read FFirstName write FFirstName;
    [Column('LAST_NAME', [cpNotNull])]
    property LastName: string read FLastName write FLastName;
    [Column('PHONE_EXT')]
    property PhoneExt: Nullable<string> read FPhoneExt write FPhoneExt;
    [Column('HIRE_DATE', [cpNotNull])]
    property HireDate: TDateTime read FHireDate write FHireDate;
    [Column('DEPT_NO', [cpNotNull])]
    property DepartmentNumber: string read FDepartmentNumber write FDepartmentNumber;
    [Column('JOB_CODE', [cpNotNull])]
    property JobCode: string read FJobCode write FJobCode;
    [Column('JOB_GRADE', [cpNotNull])]
    property JobGrade: SmallInt read FJobGrade write FJobGrade;
    [Column('JOB_COUNTRY', [cpNotNull])]
    property JobCountry: string read FJobCountry write FJobCountry;
    [Column('SALARY', [cpNotNull])]
    property Salary: Extended read FSalary write FSalary;
  end;

implementation

end.

